name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.17.4
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.4'
      - name: Install yarn and build
        run: |
          yarn
          yarn build
        env:
          CI: true